### ISSUE TITLE
Add Nuxt Support 

### ISSUE THREAD

**Issue by Kae-Tempest** [lpgera/dirigera#3]
Hello,

Can you add Nuxt support for the moment i can't use dirigera libs on Nuxt app because  os.networkInterfaces is not a function`

![image](https://github.com/lpgera/dirigera/assets/73745621/5f022966-7364-495e-93da-3e587d13848b)
![image](https://github.com/lpgera/dirigera/assets/73745621/d48239dc-3085-4e1e-820e-359ed91959ef)

**Comment by Kae-Tempest** [comment]
If we add GatewayIP have these error.. 

![image](https://github.com/lpgera/dirigera/assets/73745621/a0d163bf-5cea-4477-84d0-416cde5759de)
![image](https://github.com/lpgera/dirigera/assets/73745621/428dcd38-edf4-45ed-84d7-1f0fa6bbc69e)

**Comment by lpgera** [comment]
Hi @Kae-Tempest!

I'm not an expert in Nuxt, but to me it looks like you're trying to use `dirigera` in the browser which is not supported. You should limit the library usage to the server-side Node.js environment and it should work fine.

I'm closing this issue for now, but let me know if my assumption is wrong and you have other indicators that the error is indeed in the library code.
