### ISSUE TITLE
transitionTime does not seem supported 

### ISSUE THREAD

**Issue by kiterwork** [lpgera/dirigera#4]
Heyo!
Ive been messing around with the library and found out that client.devices.setAttributes never takes the transitionTime attribute into consideration. My code is as follows

```
await client.devices.setAttributes({
        id: 'deviceid',
        attributes: {"lightLevel": 9, transitionTime: 100000}
      })
```
But the time taken is approximately 1 second regardless of the time provided in transitionTime. I cant seem to figure out any further way to log internal errors, so i hope you are able to point me in the right direction

**Comment by kiterwork** [comment]
![image](https://github.com/lpgera/dirigera/assets/107297392/9c1b6c6f-d888-4376-9306-dff1f60b705b)
looks like this could be the culprit?

**Comment by kiterwork** [comment]
Update i got it to work with the following code
```
await client.deviceSets.setAttributes({
        id: deviceSets[0].id,
        attributes: {
            lightLevel: 1
        },
        transitionTime: 10000
    })
```
Seems like theres something different in client.devices.setAttributes versus client.deviceSets.setAttributes

**Comment by kiterwork** [comment]
Final update before closing: the docs are messed up, the syntax should be updated. lll make a pr.

**Comment by lpgera** [comment]
Sorry for the inconvenience, and thanks for your investigation! I hope I'll have time to check your findings and the PR by tomorrow! 🙂

**Comment by kiterwork** [comment]
Hey! I forgot to update here, but i was a total idiot and the code is totally fine in the docs. The issue was that the setAttributes section didnt include example code so i didnt know i had to split the transitiontime outside of the attributes object.

**Comment by lpgera** [comment]
> The issue was that the setAttributes section didnt include example code so i didnt know i had to split the transitiontime outside of the attributes object.

Noted! I'll try to make this clearer in the future.

I'm curious, are you using TypeScript in your own code? That, while doesn't replace a good documentation, but should help with these types of problems a little bit:
<img width="1034" alt="image" src="https://github.com/lpgera/dirigera/assets/3627084/7e18f0d7-55d6-4c5f-ad93-10e44c3c93ee">
