### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kiterwork** [lpgera/dirigera#6]
Heyo, is there no way to query the on/off state of a device?
As of right now im querying all devices from my client and filtering for the ones that are part of the deviceSet that carries the same id as the deviceSet im looking for, then testing their states but this seems awfully janky.

**Comment by lpgera** [comment]
Hi!

> is there no way to query the on/off state of a device?

To query the state of a specific light device you can use the `client.lights.get({ id: 'YOUR_DEVICE_ID' })` method which will give you the light object with all of its current attributes, including the `isOn` boolean attribute.

> the deviceSet im looking for

For _device sets_ however, the Dirigera gateway doesn't currently provide an endpoint to list the included devices. It may change in the future, but for now I recommend doing exactly what you described: listing all devices and filtering by the id of the device set.

**Comment by kiterwork** [comment]
Aww shucks, yeah that works. Another thing, just to save us from having to create another issue:
Do we need to turn the lights on before being able to set their lightLevel or am i missing something elsewhere?

**Comment by lpgera** [comment]
Yes, that's my experience with the gateway as well unfortunately. It's been like this with the old Tradfri gateway too, so I'm assuming that it's more of a limitation of the lightbulbs rather than the Dirigera gateway.

**Comment by kiterwork** [comment]
Dang it. More of a pain, but workable tbh. Thanks for making this all btw, its been a great help! Never got any of the other auth methods to work, so im happy this one worked and the package works well haha

Is this the same if we set devices to ison: false? If i use the following code it sometimes just stops working alltogether 
```
await client.deviceSets.setAttributes({
id: id,
attributes: {
    lightLevel: lightLevel == 0 ? 1 : lightLevel
},
transitionTime: transitionTime
})

if(lightLevel == 0){
console.log(`Turn deviceset off`)

await client.deviceSets.setIsOn({
    id: id,
    isOn: false,
})
            }
```
 Without ever actually turning off the lights, as if its getting caught up on the transition and then stops doing both operations

**Comment by kiterwork** [comment]
Ill include the full function as well as the logs from the event listener here. Im trying to make it slowly fade to being in the off state, so using 1 as my lightlevel to dim towards, to then set the lights to off

```
//check if device is on, if lightlevel > 0, set to correct lightLevel
            //if device is off, turn on and set to correct lightLevel
            const deviceSet = (await client.deviceSets.list()).find(i => i.id == id)
            //get all devices in set
            const devices = (await client.devices.list()).filter(i => i.deviceSet.find(d => d.id == id))
            const allDevicesOn = devices.every(device => device.isOn)
            console.log(`allDevicesOn: ${allDevicesOn}`)
            if(!allDevicesOn){//if not all are on, turn all on
                await client.deviceSets.setIsOn({
                    id: id,
                    isOn: true,
                })
            }
            //set lightLevel regardless of if statement
            console.log(id, lightLevel, transitionTime)
            console.log(lightLevel == 0 ? 1 : lightLevel)
            await client.deviceSets.setAttributes({
                id: id,
                attributes: {
                    lightLevel: lightLevel == 0 ? 1 : lightLevel
                },
                transitionTime: transitionTime
            })
            console.log(`before sleep`)
            await sleep(transitionTime + 1000)
            console.log(`after sleep`)

            if(lightLevel == 0){
                console.log(`Turn deviceset off`)

                await client.deviceSets.setIsOn({
                    id: id,
                    isOn: false,
                })
            }
```
```
allDevicesOn: false
8f351b71-ddf7-40ee-85f4-58b7b7caaf8b 0 1000
1
before sleep
{"id":"8aad9c15-95ab-4cf0-a0ab-1078a7f72249","time":"2024-01-02T15:44:45.000Z","specversion":"3.145.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"4005bc16-f319-44b0-a288-2b419e9e64c9_1","type":"light","deviceType":"light","createdAt":"2023-12-30T09:16:09.000Z","isReachable":true,"lastSeen":"2024-01-02T16:44:45.000Z","attributes":{"lightLevel":90},"remoteLinks":[]}}
{"id":"62cb202b-5cd2-4532-bef7-ebd668b4dc2a","time":"2024-01-02T15:44:45.000Z","specversion":"3.145.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"7f75463a-6120-43b8-80df-e3f1fdfc3571_1","type":"light","deviceType":"light","createdAt":"2023-12-30T09:15:01.000Z","isReachable":true,"lastSeen":"2024-01-02T16:44:45.000Z","attributes":{"lightLevel":90},"remoteLinks":[]}}
after sleep
Turn deviceset off
{"id":"8dc23978-5f3e-4053-8b4a-c68125198a29","time":"2024-01-02T15:44:47.000Z","specversion":"3.145.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"7f75463a-6120-43b8-80df-e3f1fdfc3571_1","type":"light","deviceType":"light","createdAt":"2023-12-30T09:15:01.000Z","isReachable":true,"lastSeen":"2024-01-02T16:44:47.000Z","attributes":{"isOn":false},"remoteLinks":[]}}
{"id":"69ece891-69be-4fc5-bf24-669654c17f06","time":"2024-01-02T15:44:47.000Z","specversion":"3.145.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"4005bc16-f319-44b0-a288-2b419e9e64c9_1","type":"light","deviceType":"light","createdAt":"2023-12-30T09:16:09.000Z","isReachable":true,"lastSeen":"2024-01-02T16:44:47.000Z","attributes":{"isOn":false},"remoteLinks":[]}}
{"id":"1f0cb438-841c-4eda-8f26-d25492016fb3","time":"2024-01-02T15:44:47.000Z","specversion":"3.145.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"4005bc16-f319-44b0-a288-2b419e9e64c9_1","type":"light","deviceType":"light","createdAt":"2023-12-30T09:16:09.000Z","isReachable":true,"lastSeen":"2024-01-02T16:44:47.000Z","attributes":{"lightLevel":1},"remoteLinks":[]}}
{"id":"152f0138-407a-487a-9fd4-0ca5cf130112","time":"2024-01-02T15:44:47.000Z","specversion":"3.145.0","source":"urn:com:ikea:homesmart:iotc:zigbee","type":"deviceStateChanged","data":{"id":"7f75463a-6120-43b8-80df-e3f1fdfc3571_1","type":"light","deviceType":"light","createdAt":"2023-12-30T09:15:01.000Z","isReachable":true,"lastSeen":"2024-01-02T16:44:47.000Z","attributes":{"lightLevel":1},"remoteLinks":[]}}
```

It seems to always emit the isOn as false before emitting the state change to lightLevel 1 unless I delay the setOn to false with an additional 5 seconds added to the transitionTime. Looks like the package isnt actually awaiting the setAttributes in this case?

**Comment by lpgera** [comment]
I think your problem most probably is that even though you await the Promise of the first command (`setAttributes`) it clashes with the second command (`setIsOn`).

The reason is that the first promise gets resolved as soon as the request to the gateway is successful. It won't wait for the transition to be complete before allowing your code to jump to the second step.

You can try adding a delay of the same amount as the transition time of the first command before running the second command.
