### ISSUE TITLE
dirigera webpage question

### ISSUE THREAD

**Issue by pepernut02** [lpgera/dirigera#9]
Hey there

for my final school project I'm making a webpage from where I can control Iot devices but I barely found any documentation on IKEA API. I read through your documentation but I had a hard time telling which parts I could use in my project.

it would really help if you could provide a simple example, including initial configuration and how to set up, e.g.,  environment variables to open/close the IKEA smart wall socket.

thanks in advance

**Comment by lpgera** [comment]
Hi @pepernut02!

> but I barely found any documentation on IKEA API

I don't think IKEA's internal API is documented anywhere publicly. That's one of the reasons I'm working on this library, so people can integrate their JS/TS apps with the Dirigera hub.

> it would really help if you could provide a simple example, including initial configuration and how to set up, e.g., environment variables to open/close the IKEA smart wall socket.

Could you tell me which part of the [Quick start in the Readme](https://github.com/lpgera/dirigera?tab=readme-ov-file#quick-start) is that you're having trouble with?

**Comment by pepernut02** [comment]
The Readme worked like it should have but i was trying to find a command i could use on that webpage something along the lines of what "shelly" does (http://"ip"/?0turn=on (to turn a device on)) so i can integrate it in code i wrote. and i thought maybe you knew a way since you made this library.

**Comment by lpgera** [comment]
I think I still don't fully understand what exactly you need assistance with, apologies.

Are you're looking for a way to control devices via a REST API? If so, then you can dig into my library's code and construct requests directly to your hub based on that. (For example [here's the part](https://github.com/lpgera/dirigera/blob/main/src/api/outlets.ts#L20-L32) which is used for turning an outlet on/off, and [here's the part responsible for the base URL and the token header](https://github.com/lpgera/dirigera/blob/main/src/index.ts#L83-L90).)

**Comment by pepernut02** [comment]
I looked through it but i didn't recognise that was the part i was looking for.
Thank you for the help.
Have a nice day.
